[package]
name = "foosball-rating"
version = "0.1.0"
authors = ["Bjarke Sørensen <bs@wasd.dk>",
    "Lucas Falch Sørensen <lucas@wasd.dk"]

[dependencies]
pencil = "*"
bbt = "0.1.0"
rustc-serialize = "0.3"
env_logger = "*"
rand = "*"
rusqlite = "0.7.3"
time = "~0.1.0"
